[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "历程"
  pageRef = "journey"
  weight = 30

[[main]]
  name = "文档"
  pageRef = "docs"
  weight = 35

[[main]]
  name = "友链"
  pageRef = "friends"
  weight = 38

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/yueludanfeng"
  weight = 90

[[footer]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "历程"
  pageRef = "journey"
  weight = 30

[[footer]]
  name = "文档"
  pageRef = "docs"
  weight = 35

[[footer]]
  name = "友链"
  pageRef = "friends"
  weight = 38

[[footer]]
  name = "关于"
  pageRef = "about"
  weight = 40

[[main]]
  name = "AI 相关"
  pageRef = "ai"
  weight = 36

[[footer]]
  name = "AI 相关"
  pageRef = "ai"
  weight = 36
