[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 50

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/"
  weight = 90

[[footer]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "关于"
  pageRef = "about"
  weight = 40
